config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # get 'lists', to: 'lists#index'
  # get "lists/new", to: 'lists#new'
  # get 'lists/:id', to: 'lists#show', as: :list
  # post "lists", to: 'lists#create'

  root 'lists#index'
  resources :lists, only: %i[index new show create] do
    resources :bookmarks, only: %i[new create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :delete_all

  validates :title, :overview, uniqueness: true
  validates :title, :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save
    redirect_to list_path(@list)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.where(list_id:params[:id])
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def list
    @lists = Movie.all
  end

  def new
    @list = List.new
  end

  def create
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    # raise
    redirect_to lists_path(@movie.list), status: :see_other
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :list %>
  <%= f.association :movie %>
  <%= f.submit "Submit Bookmark", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="navbar">
      <div class="logo">
        <%= image_tag("popcorn.png", width: "50") %>
      </div>
      <div class="helpers">
        <%= link_to 'My lists', lists_path %>
        <%= link_to 'New list', new_list_bookmark_path(List.last.id) %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>All Lists</h1>
<p><% @lists.each do |list| %></p>
  <%= link_to list.name, list_path(list) %>
<% end %>

app/views/lists/new.html.erb
<%= form_for(@list) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<div class="container">
  <h1><%= @list.name %></h1>

  <p>Movies with <%= @list.name %></p>
  <% @bookmark.each do |movie| %>
    <div class="card w-50">
      <%= image_tag(movie.movie.poster_url) %>
      <p><b><%= movie.movie.title %> - <%= movie.movie.rating %>/5</b></p>
      <p><%= movie.movie.overview %></p>
      <p>"<%= movie.comment %>"</p>
      <%= link_to "Delete", bookmark_path(movie),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    </div>
  <% end %>
</div>

app/views/movies/list.html.erb
<h1>All Lists</h1>
<p><% @lists.each do |list| %></p>
  <p><%= list.name %></p>
<% end %>